name: Deploy speific  React App on FCC ubuntu server

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Enter the tag version (e.g., 1.2.3) to build from without the v"
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: "v${{github.event.inputs.tag }}"

      - name: Install Dependencies
        run: npm install --force

      - name: Build React App
        run: npm run build

      - name: Add AWS host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to AWS Instance
        env:
          HOST: ${{ secrets.AWS_HOST }} 
          USER: ${{ secrets.AWS_USER }} 
          SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
          scp -i key.pem -r build/* $USER@$HOST:/var/www/my-react-app/
