name: FCC Build and Release

on:
  push:
    branches:
      - "master"

env:
  project-directory: ./

jobs:
  client:
    name: Build Client Project
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'skip-ci') && !contains(needs.prepare.outputs.NO_NEED_TO_BUILD, 'true')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: npm clean install
        run: npm ci --legacy-peer-deps

      - name: run ESLint
        run: npm run lint
        working-directory: ${{ env.project-directory }}
      - name: build client dev project
        run: npm run build:dev
        working-directory: ${{ env.project-directory }}

      - name: build client project
        run: npm run build
        working-directory: ${{ env.project-directory }}

      - name: run React tests
        run: npm test
        working-directory: ${{ env.project-directory }}

  release:
    name: Release semantic version
    needs: [client]
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'skip-ci')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"

      - name: Install Semantic Release
        run: npm i -g semantic-release @semantic-release/{git,exec,changelog}

      - name: Run Semantic Release
        run: semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
